version: '3.7'

networks:
  app:
    name: app

services:
  rails-dummy_app:
    container_name: ${PROJECT_NAME}_app
    build:
      context: .
      target: build_ruby
      dockerfile: docker/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - rails-dummy_mysql
    networks:
      - app

  rails-dummy_mysql:
    image: mariadb:10.4
    container_name: ${PROJECT_NAME}_mysql
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute "show databases"
      interval: 5s
      timeout:  1s
      retries:  3
    ports:
      - 3306:3306
    networks:
      - app
