development:
    secret_key_base: 0d37f5066c1ae66c7a72fc012deb45db0a434f91

test:
    secret_key_base: a6a28b034819200ccff1a83832f5b271a59108ab

production:
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
